---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: blogsite
  namespace: engineering
spec:
  routes:
  - services:
    - name: wwwblog
      port: 80
    conditions:
      - prefix: /api