apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: containersteve-tls-wild
  namespace: root-proxies
spec:
  acme:
    config:
    - dns01:
        provider: route53
      domains:
      - '*.pixelproxy.net'
      - pixelproxy.net
  commonName: '*.pixelproxy.net'
  dnsNames:
  - pixelproxy.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-dns
  secretName: demoprojectcontourio-tls-wild