apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: gimbal
    namespace: projectcontour
  spec:
    ports:
    - name: gimbal
      port: 80
      protocol: TCP
      targetPort: 80
    type: ClusterIP
- apiVersion: v1
  kind: Endpoints
  metadata:
    name: gimbal
    namespace: projectcontour
  subsets:
  - addresses:
    - ip: GIMBALIP
    ports:
    - name: gimbal
      port: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gimbal
  namespace: projectcontour
spec:
  backend:
    serviceName: gimbal
    servicePort: 80