apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: marketing
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: stevesloka/echo-server
        command: ["echo-server"]
        args:
          - --echotext=This is the GREEN cluster!
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: web
 namespace: marketing
spec:
 ports:
 - port: 80
   name: http
   targetPort: 8080
   protocol: TCP
 selector:
   app: web
 type: ClusterIP
