apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tunnels.inlets.inlets.dev
spec:
  group: inlets.inlets.dev
  version: v1alpha1
  names:
    kind: Tunnel
    plural: tunnels
  scope: Namespaced
