apiVersion: v1
kind: Namespace
metadata:
  name: root-proxies
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata: 
  name: web-main
  namespace: root-proxies
spec: 
  virtualhost:
    fqdn: pixelproxy.net
  includes:
  - name: default-proxy
    namespace: marketing
    conditions:
    - prefix: /
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata: 
  name: default-proxy
  namespace: marketing
spec: 
  routes: 
    - services: 
        - name: vmware-web
          port: 80