apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: root
  namespace: root-proxies
spec:
  virtualhost:
    fqdn: marketing.pixelproxy.io
  includes:
  - name: marketingroot
    namespace: marketing
    conditions:
    - prefix: /
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: marketingroot
  namespace: marketing
spec: 
  routes: 
  - services: 
    - name: vmware-windows
      port: 80










  # - services:
  #   - name: secureapp
  #     port: 80
  #   conditions:
  #     - prefix: /secure
  #     - header:
  #         name: User-Agent
  #         notcontains: Firefox
  #     - header:
  #         name: User-Agent
  #         notcontains: Chrome
    
    






  #         name: User-Agent
  #         notcontains: Chrome


  # includes:
  # - name: blogsite
  #   namespace: marketing
  #   conditions:
  #   - prefix: /blog
  #   - header:
  #       name: x-header
  #       exact: abc