apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: internal-api
  namespace: marketing
spec: 
  virtualhost:
    fqdn: api.marketing.contour
  routes: 
  - services: 
    - name: vmware-api
      port: 80
