---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: marketing
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: stevesloka/echo-server
        command: ["echo-server"]
        args:
          - --echotext=This is the BLUE cluster!
        ports:
        - containerPort: 8080
        env:
        - name: API_URL
          value: http://api.marketing.contour