---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata: 
  name: blog
  namespace: marketing
spec: 
  routes: 
  - conditions:
    - prefix: /blog
    services: 
      - name: blue
        port: 80